# Generated by Django 5.2.5 on 2025-08-09 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('distance_miles', models.FloatField()),
                ('duration_minutes', models.FloatField()),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('avg_pace_min_per_mile', models.FloatField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
